kind: Service
apiVersion: v1
metadata:
  name: deis-etcd-discovery-$(.name)
  labels:
    name: deis-etcd-discovery-$(.name)
    app: deis
spec:
  ports:
    - name: client
      port: 2381
  selector:
    name: deis-etcd-discovery-$(.name)
