apiVersion: v1
kind: ReplicationController
metadata:
  name: deis-etcd-$(.name)
spec:
  replicas: $(.initialReplicas)
  selector:
    name: deis-etcd-$(.name)
    mode: cluster
    provider: redis-$(.name)
  template:
    metadata:
      labels:
        name: deis-etcd-$(.name)
    spec:
      containers:
        - name: deis-etcd-$(.name)
          image: quay.io/deisci/etcd:v2-beta
          imagePullPolicy: Always
          env:
            - name: DEIS_ETCD_CLUSTER_SIZE
              value: "$(.initialReplicas)"
            - name: ETCD_NAME
              value: deis-etcd-$(.name)
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: discovery-token-$(.name)
              readOnly: true
              mountPath: /var/run/secrets/deis/etcd/discovery
      volumes:
        - name: discovery-token-$(.name)
          secret:
            secretName: deis-etcd-discovery-$(.name)-token
