kind: Service
apiVersion: v1
metadata:
  name: deis-etcd-$(.name)
  labels:
    name: deis-etcd-$(.name)
    app: deis
spec:
  ports:
    - name: peer
      port: 2380
      protocol: TCP
    - name: client
      port: $(.port)
  selector:
    name: deis-etcd-$(.name)
